using System.Linq;
using System.Text;
using DRPC.CodeGenerator.Metadata;

namespace DRPC.CodeGenerator.Emitter;

/// <summary>
/// Renders the generated code for a single partial hub.
/// Layout: constructor (receive registration) → connect/listen → payload helpers →
/// outgoing stubs → incoming dispatch.
/// </summary>
internal static partial class RpcHubEmitter
{
    const string SessionFactoryType =
        "global::System.Func<global::DRPC.Shared.Network.HubBase, global::Communication.Shared.Sessions.ISession>";

    /// <summary>Renders the full generated partial class source for the hub.</summary>
    public static string Emit(TypeMetadata model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by DRPC.CodeGenerator. Do not modify manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        string indent = "";
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        EmitPartialClass(sb, model, indent);

        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    /// <summary>
    /// Minimal skeleton emitted when validation fails. Keeps the user's {Method}_Implementation/
    /// _Validate partials from losing their definitions (which would produce a wall of CS0759
    /// follow-up errors) — the build failure itself is already covered by the reported diagnostic.
    /// </summary>
    public static string EmitSkeleton(TypeMetadata model)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("// Generated by DRPC.CodeGenerator. Do not modify manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        bool hasNamespace = !string.IsNullOrEmpty(model.Namespace);
        string indent = "";
        if (hasNamespace)
        {
            sb.AppendLine($"namespace {model.Namespace}");
            sb.AppendLine("{");
            indent = "    ";
        }

        sb.AppendLine($"{indent}public partial class {model.Symbol.Name}");
        sb.AppendLine($"{indent}{{");

        string inner = indent + "    ";

        // Satisfies the base (ServerHub/ClientHub) required constructor. Skipped when the user
        // declared one (same condition as the regular emitter).
        if (model.Symbol.InstanceConstructors.All(static c => c.IsImplicitlyDeclared))
        {
            sb.AppendLine($"{inner}public {model.Symbol.Name}({SessionFactoryType} sessionFactory)");
            sb.AppendLine($"{inner}    : base(sessionFactory)");
            sb.AppendLine($"{inner}{{");
            sb.AppendLine($"{inner}}}");
            sb.AppendLine();
        }

        foreach (MethodMetadata method in model.Incoming)
        {
            sb.AppendLine($"{inner}private partial {method.ImplementationSignature};");
            if (method.Validation)
            {
                sb.AppendLine($"{inner}private partial {method.ValidateSignature};");
            }
        }

        sb.AppendLine($"{indent}}}");
        if (hasNamespace)
        {
            sb.AppendLine("}");
        }

        return sb.ToString();
    }

    static void EmitPartialClass(StringBuilder sb, TypeMetadata model, string indent)
    {
        string hub = model.Symbol.Name;

        sb.AppendLine($"{indent}public partial class {hub}");
        sb.AppendLine($"{indent}{{");

        string inner = indent + "    ";

        EmitConstructor(sb, model, inner);

        if (model.IsServerEndpoint)
        {
            EmitListenAsync(sb, hub, inner);
        }
        else
        {
            EmitConnectAsync(sb, hub, inner);
        }

        foreach (MethodMetadata method in model.ServerDeclarations.Methods.Concat(model.ClientDeclarations.Methods))
        {
            if (method.IsGeneric)
            {
                EmitGenericPayloadHelpers(sb, method, inner);
            }
            else
            {
                EmitPayloadHelpers(sb, method, inner);
            }
        }

        foreach (MethodMetadata method in model.Outgoing)
        {
            if (method.IsGeneric)
            {
                EmitGenericOutgoing(sb, method, inner);
            }
            else
            {
                EmitOutgoing(sb, method, inner);
            }
        }

        foreach (MethodMetadata method in model.Incoming)
        {
            if (method.IsGeneric)
            {
                EmitGenericIncoming(sb, method, inner);
            }
            else
            {
                EmitIncoming(sb, method, inner);
            }
        }

        sb.AppendLine($"{indent}}}");
    }

    static void EmitConstructor(StringBuilder sb, TypeMetadata model, string indent)
    {
        string hub = model.Symbol.Name;

        // Skipped when the user declared a constructor, to avoid a collision
        // (that constructor must accept the session factory).
        if (!model.Symbol.InstanceConstructors.All(static c => c.IsImplicitlyDeclared))
        {
            return;
        }

        sb.AppendLine($"{indent}public {hub}({SessionFactoryType} sessionFactory)");
        sb.AppendLine($"{indent}    : base(sessionFactory)");
        sb.AppendLine($"{indent}{{");
        foreach (MethodMetadata method in model.Incoming)
        {
            sb.AppendLine($"{indent}    MethodCallActions.Add({method.MethodId}, {method.MethodName}_Requested);");
            sb.AppendLine($"{indent}    MethodDeliveryModes[{method.MethodId}] = {method.ModeExpression};");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    static void EmitConnectAsync(StringBuilder sb, string hub, string indent)
    {
        string connectBody =
            $"channel => new {hub}(h => global::DRPC.Shared.Network.HubSessionFactory.CreateRudpSession(channel, h))";

        sb.AppendLine($"{indent}/// <summary>Connects to the server and creates a hub. Defined only on generated hubs (not inherited from the base class).</summary>");
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<{hub}> ConnectAsync(string host, int port, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => ConnectAsync(host, port, (string?)null, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<{hub}> ConnectAsync(string host, int port, string? connectionKey, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Client.Network.RpcClient.ConnectAsync(host, port, connectionKey, {connectBody}, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>Connects with transport options (key, DTLS, timeout, etc.) specified in bulk via RpcEndpointOptions.</summary>");
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<{hub}> ConnectAsync(string host, int port, global::DRPC.Shared.Network.RpcEndpointOptions options, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Client.Network.RpcClient.ConnectWithOptionsAsync(host, port, options, {connectBody}, cancellationToken);");
        sb.AppendLine();
    }

    static void EmitListenAsync(StringBuilder sb, string hub, string indent)
    {
        string listenFactory =
            $"channel => new {hub}(h => global::DRPC.Shared.Network.HubSessionFactory.CreateRudpSession(channel, h))";

        sb.AppendLine($"{indent}/// <summary>Listens on the port and creates a hub per peer. Disposing the returned handle stops the listener and disposes all peers.</summary>");
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<global::DRPC.Shared.Network.RpcListenHandle> ListenAsync(int port, global::System.Func<{hub}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => ListenAsync(port, (string?)null, onConnected, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<global::DRPC.Shared.Network.RpcListenHandle> ListenAsync(int port, string? connectionKey, global::System.Func<{hub}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Server.Network.RpcHost.ListenAsync(port, connectionKey, {listenFactory}, onConnected, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}/// <summary>Listens with transport options (key, DTLS, timeout, etc.) specified in bulk via RpcEndpointOptions.</summary>");
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<global::DRPC.Shared.Network.RpcListenHandle> ListenAsync(int port, global::DRPC.Shared.Network.RpcEndpointOptions options, global::System.Func<{hub}, global::System.Threading.Tasks.Task> onConnected, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Server.Network.RpcHost.ListenWithOptionsAsync(port, options, {listenFactory}, onConnected, cancellationToken);");
        sb.AppendLine();
        sb.AppendLine($"{indent}public static global::System.Threading.Tasks.Task<global::DRPC.Shared.Network.RpcListenHandle> ListenAsync(int port, global::System.Threading.CancellationToken cancellationToken = default)");
        sb.AppendLine($"{indent}    => global::DRPC.Server.Network.RpcHost.ListenAsync(port, null, {listenFactory}, null, cancellationToken);");
        sb.AppendLine();
    }

    static void EmitOutgoing(StringBuilder sb, MethodMetadata method, string indent)
    {
        string args = string.Join(", ", method.Parameters.Select(static p => p.Name));
        string asyncReturn = method.IsVoidReturn || method.OneWay
            ? "global::System.Threading.Tasks.Task"
            : $"global::System.Threading.Tasks.Task<{method.ReturnTypeDisplay}>";

        // Round-trip calls take a caller cancellation token (optional last parameter).
        // One-way sends have no wait, so they omit it.
        string ctParam = method.OneWay ? "" : CancellationTokenParam(method);

        sb.AppendLine($"{indent}public async {asyncReturn} {method.MethodName}Async({method.ParameterDeclarationList()}{ctParam})");
        sb.AppendLine($"{indent}{{");
        EmitPayloadWrite(sb, indent + "    ", method, args, "__payload");

        if (method.OneWay)
        {
            sb.AppendLine($"{indent}    await SendRPC({method.MethodId}, __payload, {method.ModeExpression}).ConfigureAwait(false);");
        }
        else if (method.IsVoidReturn)
        {
            sb.AppendLine($"{indent}    await RequestRPC({method.MethodId}, __payload, {method.ModeExpression}{TimeoutArg(method)}, cancellationToken).ConfigureAwait(false);");
        }
        else
        {
            sb.AppendLine($"{indent}    byte[] __response = await RequestRPC({method.MethodId}, __payload, {method.ModeExpression}{TimeoutArg(method)}, cancellationToken).ConfigureAwait(false);");
            sb.AppendLine($"{indent}    return {ReadReturn(method)}(__response);");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
    }

    /// <summary>The optional cancellation-token parameter appended to the end of round-trip stubs (without a leading comma for parameterless methods).</summary>
    static string CancellationTokenParam(MethodMetadata method)
        => (method.Parameters.Length == 0 ? "" : ", ")
            + "global::System.Threading.CancellationToken cancellationToken = default";

    /// <summary>
    /// Per-call timeout argument (including the leading comma). Empty string when TimeoutMs is
    /// unset (-1) — byte-identical to previously generated text. When positive, inserts
    /// <c>TimeSpan.FromMilliseconds(N)</c> after the delivery-mode argument (shared by the
    /// generic and non-generic emitters).
    /// </summary>
    internal static string TimeoutArg(MethodMetadata method)
        => method.TimeoutMs > 0
            ? $", global::System.TimeSpan.FromMilliseconds({method.TimeoutMs})"
            : "";

    static void EmitIncoming(StringBuilder sb, MethodMetadata method, string indent)
    {
        sb.AppendLine($"{indent}private async global::System.Threading.Tasks.Task<byte[]> {method.MethodName}_Requested(byte[] __parameterData)");
        sb.AppendLine($"{indent}{{");
        string args = "";
        if (method.Parameters.Length > 0)
        {
            for (int i = 0; i < method.Parameters.Length; i++)
            {
                sb.AppendLine($"{indent}    {method.Parameters[i].Type.ToDisplayString(RpcPayload.Qualified)} {method.Parameters[i].Name} = default!;");
            }

            string outs = string.Join(", ", method.Parameters.Select(p => $"out {p.Name}"));
            sb.AppendLine($"{indent}    {ReadParams(method)}(__parameterData, {outs});");
            args = string.Join(", ", method.Parameters.Select(static p => p.Name));
        }

        EmitValidationGate(sb, method, args, indent + "    ");

        if (method.IsVoidReturn)
        {
            sb.AppendLine($"{indent}    await {method.MethodName}_Implementation({args}).ConfigureAwait(false);");
            sb.AppendLine($"{indent}    return global::System.Array.Empty<byte>();");
        }
        else
        {
            sb.AppendLine($"{indent}    {method.ReturnTypeDisplay} __result = await {method.MethodName}_Implementation({args}).ConfigureAwait(false);");
            sb.AppendLine($"{indent}    return {WriteReturn(method)}(__result);");
        }

        sb.AppendLine($"{indent}}}");
        sb.AppendLine();
        sb.AppendLine($"{indent}private partial {method.ImplementationSignature};");
        EmitValidateDeclaration(sb, method, indent);
    }

    /// <summary>The _Validate gate for Validation=true methods — a false return throws ValidationFailed and the implementation is never called. Generics pass closed type arguments via typeArgs.</summary>
    internal static void EmitValidationGate(StringBuilder sb, MethodMetadata method, string args, string indent, string typeArgs = "")
    {
        if (!method.Validation)
        {
            return;
        }

        sb.AppendLine($"{indent}if (!await {method.MethodName}_Validate{typeArgs}({args}).ConfigureAwait(false))");
        sb.AppendLine($"{indent}{{");
        sb.AppendLine($"{indent}    throw new global::DRPC.Shared.RpcValidationFailedException(\"{method.MethodName}\");");
        sb.AppendLine($"{indent}}}");
    }

    /// <summary>When Validation=true, adds the _Validate partial declaration (compile error if unimplemented — fail-closed).</summary>
    internal static void EmitValidateDeclaration(StringBuilder sb, MethodMetadata method, string indent)
    {
        if (!method.Validation)
        {
            return;
        }

        sb.AppendLine($"{indent}private partial {method.ValidateSignature};");
        sb.AppendLine();
    }

    // ── Payload helper names ─────────────────────────────────────────────

    static string WriteParams(MethodMetadata m) => $"__WriteParams_{m.DeclarationName}_{m.MethodName}";

    static string ReadParams(MethodMetadata m) => $"__ReadParams_{m.DeclarationName}_{m.MethodName}";

    static string WriteReturn(MethodMetadata m) => $"__WriteReturn_{m.DeclarationName}_{m.MethodName}";

    static string ReadReturn(MethodMetadata m) => $"__ReadReturn_{m.DeclarationName}_{m.MethodName}";
}
